package com.book.model;

import com.framework.model.BaseModel;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table booktyperelation
 *
 * @mbg.generated do_not_delete_during_merge Mon Sep 30 10:55:26 CST 2019
 */
public class Booktyperelation extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     * 主键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktyperelation.IdRelation
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String idRelation;

    /**
     * Database Column Remarks:
     * 书籍ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktyperelation.IdBook
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String idBook;

    /**
     * Database Column Remarks:
     * 书籍类型ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktyperelation.IdBookType
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String idBookType;

    /**
     * Database Column Remarks:
     * 关联时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktyperelation.RelationTime
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private Date relationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktyperelation.remark
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table booktyperelation
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktyperelation.IdRelation
     *
     * @return the value of booktyperelation.IdRelation
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getIdRelation() {
        return idRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktyperelation.IdRelation
     *
     * @param idRelation the value for booktyperelation.IdRelation
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setIdRelation(String idRelation) {
        this.idRelation = idRelation == null ? null : idRelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktyperelation.IdBook
     *
     * @return the value of booktyperelation.IdBook
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getIdBook() {
        return idBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktyperelation.IdBook
     *
     * @param idBook the value for booktyperelation.IdBook
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setIdBook(String idBook) {
        this.idBook = idBook == null ? null : idBook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktyperelation.IdBookType
     *
     * @return the value of booktyperelation.IdBookType
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getIdBookType() {
        return idBookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktyperelation.IdBookType
     *
     * @param idBookType the value for booktyperelation.IdBookType
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setIdBookType(String idBookType) {
        this.idBookType = idBookType == null ? null : idBookType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktyperelation.RelationTime
     *
     * @return the value of booktyperelation.RelationTime
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public Date getRelationTime() {
        return relationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktyperelation.RelationTime
     *
     * @param relationTime the value for booktyperelation.RelationTime
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setRelationTime(Date relationTime) {
        this.relationTime = relationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktyperelation.remark
     *
     * @return the value of booktyperelation.remark
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktyperelation.remark
     *
     * @param remark the value for booktyperelation.remark
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktyperelation
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public Object getPrimaryKey() {
        return this.getIdRelation();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktyperelation
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idRelation=").append(idRelation);
        sb.append(", idBook=").append(idBook);
        sb.append(", idBookType=").append(idBookType);
        sb.append(", relationTime=").append(relationTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktyperelation
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Booktyperelation other = (Booktyperelation) that;
        return (this.getIdRelation() == null ? other.getIdRelation() == null : this.getIdRelation().equals(other.getIdRelation()))
                && (this.getIdBook() == null ? other.getIdBook() == null : this.getIdBook().equals(other.getIdBook()))
                && (this.getIdBookType() == null ? other.getIdBookType() == null : this.getIdBookType().equals(other.getIdBookType()))
                && (this.getRelationTime() == null ? other.getRelationTime() == null : this.getRelationTime().equals(other.getRelationTime()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktyperelation
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdRelation() == null) ? 0 : getIdRelation().hashCode());
        result = prime * result + ((getIdBook() == null) ? 0 : getIdBook().hashCode());
        result = prime * result + ((getIdBookType() == null) ? 0 : getIdBookType().hashCode());
        result = prime * result + ((getRelationTime() == null) ? 0 : getRelationTime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}