package com.book.model;

import com.framework.model.BaseModel;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table booktype
 *
 * @mbg.generated do_not_delete_during_merge Mon Sep 30 10:55:26 CST 2019
 */
public class Booktype extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.IdBookType
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String idBookType;

    /**
     * Database Column Remarks:
     *   书类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.TypeName
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.AliasName
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String aliasName;

    /**
     * Database Column Remarks:
     *   地址：记录未来的网址，或来源的网址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.TypeAddress
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String typeAddress;

    /**
     * Database Column Remarks:
     *   此类书的数量，在书确定类型时更新
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.BookNum
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private Integer bookNum;

    /**
     * Database Column Remarks:
     *   读者数量：来源分为多种，一种是配置是否关注过其中的书，另一种是阅读过多少章节后进行记录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.ReaderNum
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private Integer readerNum;

    /**
     * Database Column Remarks:
     *   父类别ID，一级类别父类为0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.ParentId
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.Remark
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table booktype
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.IdBookType
     *
     * @return the value of booktype.IdBookType
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getIdBookType() {
        return idBookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.IdBookType
     *
     * @param idBookType the value for booktype.IdBookType
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setIdBookType(String idBookType) {
        this.idBookType = idBookType == null ? null : idBookType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.TypeName
     *
     * @return the value of booktype.TypeName
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.TypeName
     *
     * @param typeName the value for booktype.TypeName
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.AliasName
     *
     * @return the value of booktype.AliasName
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.AliasName
     *
     * @param aliasName the value for booktype.AliasName
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setAliasName(String aliasName) {
        this.aliasName = aliasName == null ? null : aliasName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.TypeAddress
     *
     * @return the value of booktype.TypeAddress
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getTypeAddress() {
        return typeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.TypeAddress
     *
     * @param typeAddress the value for booktype.TypeAddress
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setTypeAddress(String typeAddress) {
        this.typeAddress = typeAddress == null ? null : typeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.BookNum
     *
     * @return the value of booktype.BookNum
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public Integer getBookNum() {
        return bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.BookNum
     *
     * @param bookNum the value for booktype.BookNum
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setBookNum(Integer bookNum) {
        this.bookNum = bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.ReaderNum
     *
     * @return the value of booktype.ReaderNum
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public Integer getReaderNum() {
        return readerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.ReaderNum
     *
     * @param readerNum the value for booktype.ReaderNum
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setReaderNum(Integer readerNum) {
        this.readerNum = readerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.ParentId
     *
     * @return the value of booktype.ParentId
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.ParentId
     *
     * @param parentId the value for booktype.ParentId
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.Remark
     *
     * @return the value of booktype.Remark
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.Remark
     *
     * @param remark the value for booktype.Remark
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public Object getPrimaryKey() {
        return this.getIdBookType();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idBookType=").append(idBookType);
        sb.append(", typeName=").append(typeName);
        sb.append(", aliasName=").append(aliasName);
        sb.append(", typeAddress=").append(typeAddress);
        sb.append(", bookNum=").append(bookNum);
        sb.append(", readerNum=").append(readerNum);
        sb.append(", parentId=").append(parentId);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Booktype other = (Booktype) that;
        return (this.getIdBookType() == null ? other.getIdBookType() == null : this.getIdBookType().equals(other.getIdBookType()))
            && (this.getTypeName() == null ? other.getTypeName() == null : this.getTypeName().equals(other.getTypeName()))
            && (this.getAliasName() == null ? other.getAliasName() == null : this.getAliasName().equals(other.getAliasName()))
            && (this.getTypeAddress() == null ? other.getTypeAddress() == null : this.getTypeAddress().equals(other.getTypeAddress()))
            && (this.getBookNum() == null ? other.getBookNum() == null : this.getBookNum().equals(other.getBookNum()))
            && (this.getReaderNum() == null ? other.getReaderNum() == null : this.getReaderNum().equals(other.getReaderNum()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdBookType() == null) ? 0 : getIdBookType().hashCode());
        result = prime * result + ((getTypeName() == null) ? 0 : getTypeName().hashCode());
        result = prime * result + ((getAliasName() == null) ? 0 : getAliasName().hashCode());
        result = prime * result + ((getTypeAddress() == null) ? 0 : getTypeAddress().hashCode());
        result = prime * result + ((getBookNum() == null) ? 0 : getBookNum().hashCode());
        result = prime * result + ((getReaderNum() == null) ? 0 : getReaderNum().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}