package com.book.model;

import com.framework.model.BaseModel;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table chaptercontent
 *
 * @mbg.generated do_not_delete_during_merge Mon Sep 30 10:55:26 CST 2019
 */
public class Chaptercontent extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chaptercontent.oriBookId
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private Integer oriBookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chaptercontent.chapterNo
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private Integer chapterNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chaptercontent.BookContent
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String bookContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chaptercontent
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chaptercontent.oriBookId
     *
     * @return the value of chaptercontent.oriBookId
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public Integer getOriBookId() {
        return oriBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chaptercontent.oriBookId
     *
     * @param oriBookId the value for chaptercontent.oriBookId
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setOriBookId(Integer oriBookId) {
        this.oriBookId = oriBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chaptercontent.chapterNo
     *
     * @return the value of chaptercontent.chapterNo
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public Integer getChapterNo() {
        return chapterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chaptercontent.chapterNo
     *
     * @param chapterNo the value for chaptercontent.chapterNo
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setChapterNo(Integer chapterNo) {
        this.chapterNo = chapterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chaptercontent.BookContent
     *
     * @return the value of chaptercontent.BookContent
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getBookContent() {
        return bookContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chaptercontent.BookContent
     *
     * @param bookContent the value for chaptercontent.BookContent
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setBookContent(String bookContent) {
        this.bookContent = bookContent == null ? null : bookContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chaptercontent
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public Object getPrimaryKey() {
        return this.getOriBookId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chaptercontent
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oriBookId=").append(oriBookId);
        sb.append(", chapterNo=").append(chapterNo);
        sb.append(", bookContent=").append(bookContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chaptercontent
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chaptercontent other = (Chaptercontent) that;
        return (this.getOriBookId() == null ? other.getOriBookId() == null : this.getOriBookId().equals(other.getOriBookId()))
            && (this.getChapterNo() == null ? other.getChapterNo() == null : this.getChapterNo().equals(other.getChapterNo()))
            && (this.getBookContent() == null ? other.getBookContent() == null : this.getBookContent().equals(other.getBookContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chaptercontent
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOriBookId() == null) ? 0 : getOriBookId().hashCode());
        result = prime * result + ((getChapterNo() == null) ? 0 : getChapterNo().hashCode());
        result = prime * result + ((getBookContent() == null) ? 0 : getBookContent().hashCode());
        return result;
    }
}