package com.book.model;

import com.framework.model.BaseModel;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table chapter
 *
 * @mbg.generated do_not_delete_during_merge Mon Sep 30 10:55:26 CST 2019
 */
public class Chapter extends BaseModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.IDChapter
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String IDChapter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.oriBookId
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private Integer oriBookId;

    /**
     * Database Column Remarks:
     * 书籍ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.BookId
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String bookId;

    /**
     * Database Column Remarks:
     * 章节名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.ChapterName
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String chapterName;

    /**
     * Database Column Remarks:
     * 章节顺序号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.ChapterOrder
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private Integer chapterOrder;

    /**
     * Database Column Remarks:
     * 原章节ID号，
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.ChapterIdNo
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private Integer chapterIdNo;

    /**
     * Database Column Remarks:
     * 原章节内容地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.ChapterAddress
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String chapterAddress;

    /**
     * Database Column Remarks:
     * 更新时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.updatetime
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private Date updatetime;

    /**
     * Database Column Remarks:
     * 是否抓取完成，抓取完章节内容，认为完成，完成状态为1，否则为0
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.IsFetchFinish
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String isFetchFinish;

    /**
     * Database Column Remarks:
     * 备注
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.remarker
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String remarker;

    /**
     * Database Column Remarks:
     * 章节内容
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.Content
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chapter
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.IDChapter
     *
     * @return the value of chapter.IDChapter
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getIDChapter() {
        return IDChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.IDChapter
     *
     * @param IDChapter the value for chapter.IDChapter
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setIDChapter(String IDChapter) {
        this.IDChapter = IDChapter == null ? null : IDChapter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.oriBookId
     *
     * @return the value of chapter.oriBookId
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public Integer getOriBookId() {
        return oriBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.oriBookId
     *
     * @param oriBookId the value for chapter.oriBookId
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setOriBookId(Integer oriBookId) {
        this.oriBookId = oriBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.BookId
     *
     * @return the value of chapter.BookId
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.BookId
     *
     * @param bookId the value for chapter.BookId
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.ChapterName
     *
     * @return the value of chapter.ChapterName
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.ChapterName
     *
     * @param chapterName the value for chapter.ChapterName
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.ChapterOrder
     *
     * @return the value of chapter.ChapterOrder
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public Integer getChapterOrder() {
        return chapterOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.ChapterOrder
     *
     * @param chapterOrder the value for chapter.ChapterOrder
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setChapterOrder(Integer chapterOrder) {
        this.chapterOrder = chapterOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.ChapterIdNo
     *
     * @return the value of chapter.ChapterIdNo
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public Integer getChapterIdNo() {
        return chapterIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.ChapterIdNo
     *
     * @param chapterIdNo the value for chapter.ChapterIdNo
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setChapterIdNo(Integer chapterIdNo) {
        this.chapterIdNo = chapterIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.ChapterAddress
     *
     * @return the value of chapter.ChapterAddress
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getChapterAddress() {
        return chapterAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.ChapterAddress
     *
     * @param chapterAddress the value for chapter.ChapterAddress
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setChapterAddress(String chapterAddress) {
        this.chapterAddress = chapterAddress == null ? null : chapterAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.updatetime
     *
     * @return the value of chapter.updatetime
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.updatetime
     *
     * @param updatetime the value for chapter.updatetime
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.IsFetchFinish
     *
     * @return the value of chapter.IsFetchFinish
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getIsFetchFinish() {
        return isFetchFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.IsFetchFinish
     *
     * @param isFetchFinish the value for chapter.IsFetchFinish
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setIsFetchFinish(String isFetchFinish) {
        this.isFetchFinish = isFetchFinish == null ? null : isFetchFinish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.remarker
     *
     * @return the value of chapter.remarker
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getRemarker() {
        return remarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.remarker
     *
     * @param remarker the value for chapter.remarker
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setRemarker(String remarker) {
        this.remarker = remarker == null ? null : remarker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.Content
     *
     * @return the value of chapter.Content
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.Content
     *
     * @param content the value for chapter.Content
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public Object getPrimaryKey() {
        return this.getIDChapter();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IDChapter=").append(IDChapter);
        sb.append(", oriBookId=").append(oriBookId);
        sb.append(", bookId=").append(bookId);
        sb.append(", chapterName=").append(chapterName);
        sb.append(", chapterOrder=").append(chapterOrder);
        sb.append(", chapterIdNo=").append(chapterIdNo);
        sb.append(", chapterAddress=").append(chapterAddress);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", isFetchFinish=").append(isFetchFinish);
        sb.append(", remarker=").append(remarker);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chapter other = (Chapter) that;
        return (this.getIDChapter() == null ? other.getIDChapter() == null : this.getIDChapter().equals(other.getIDChapter()))
                && (this.getOriBookId() == null ? other.getOriBookId() == null : this.getOriBookId().equals(other.getOriBookId()))
                && (this.getBookId() == null ? other.getBookId() == null : this.getBookId().equals(other.getBookId()))
                && (this.getChapterName() == null ? other.getChapterName() == null : this.getChapterName().equals(other.getChapterName()))
                && (this.getChapterOrder() == null ? other.getChapterOrder() == null : this.getChapterOrder().equals(other.getChapterOrder()))
                && (this.getChapterIdNo() == null ? other.getChapterIdNo() == null : this.getChapterIdNo().equals(other.getChapterIdNo()))
                && (this.getChapterAddress() == null ? other.getChapterAddress() == null : this.getChapterAddress().equals(other.getChapterAddress()))
                && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
                && (this.getIsFetchFinish() == null ? other.getIsFetchFinish() == null : this.getIsFetchFinish().equals(other.getIsFetchFinish()))
                && (this.getRemarker() == null ? other.getRemarker() == null : this.getRemarker().equals(other.getRemarker()))
                && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIDChapter() == null) ? 0 : getIDChapter().hashCode());
        result = prime * result + ((getOriBookId() == null) ? 0 : getOriBookId().hashCode());
        result = prime * result + ((getBookId() == null) ? 0 : getBookId().hashCode());
        result = prime * result + ((getChapterName() == null) ? 0 : getChapterName().hashCode());
        result = prime * result + ((getChapterOrder() == null) ? 0 : getChapterOrder().hashCode());
        result = prime * result + ((getChapterIdNo() == null) ? 0 : getChapterIdNo().hashCode());
        result = prime * result + ((getChapterAddress() == null) ? 0 : getChapterAddress().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getIsFetchFinish() == null) ? 0 : getIsFetchFinish().hashCode());
        result = prime * result + ((getRemarker() == null) ? 0 : getRemarker().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}