package com.book.model;

import java.io.Serializable;
import java.util.Arrays;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table netbook
 *
 * @mbg.generated do_not_delete_during_merge Mon Sep 30 10:55:26 CST 2019
 */
public class NetbookWithBLOBs extends Netbook implements Serializable {
    /**
     * Database Column Remarks:
     * 摘要
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netbook.BookAbstract
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private String bookAbstract;

    /**
     * Database Column Remarks:
     * 封面图片
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netbook.Cover
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private byte[] cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table netbook
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netbook.BookAbstract
     *
     * @return the value of netbook.BookAbstract
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public String getBookAbstract() {
        return bookAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netbook.BookAbstract
     *
     * @param bookAbstract the value for netbook.BookAbstract
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setBookAbstract(String bookAbstract) {
        this.bookAbstract = bookAbstract == null ? null : bookAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netbook.Cover
     *
     * @return the value of netbook.Cover
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public byte[] getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netbook.Cover
     *
     * @param cover the value for netbook.Cover
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    public void setCover(byte[] cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netbook
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bookAbstract=").append(bookAbstract);
        sb.append(", cover=").append(cover);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netbook
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NetbookWithBLOBs other = (NetbookWithBLOBs) that;
        return (this.getIdBook() == null ? other.getIdBook() == null : this.getIdBook().equals(other.getIdBook()))
                && (this.getBookName() == null ? other.getBookName() == null : this.getBookName().equals(other.getBookName()))
                && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
                && (this.getSectionNum() == null ? other.getSectionNum() == null : this.getSectionNum().equals(other.getSectionNum()))
                && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getIsFinish() == null ? other.getIsFinish() == null : this.getIsFinish().equals(other.getIsFinish()))
                && (this.getNetBookId() == null ? other.getNetBookId() == null : this.getNetBookId().equals(other.getNetBookId()))
                && (this.getOriTypeName() == null ? other.getOriTypeName() == null : this.getOriTypeName().equals(other.getOriTypeName()))
                && (this.getOrigin() == null ? other.getOrigin() == null : this.getOrigin().equals(other.getOrigin()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
                && (this.getBookAbstract() == null ? other.getBookAbstract() == null : this.getBookAbstract().equals(other.getBookAbstract()))
                && (Arrays.equals(this.getCover(), other.getCover()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netbook
     *
     * @mbg.generated Mon Sep 30 10:55:26 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdBook() == null) ? 0 : getIdBook().hashCode());
        result = prime * result + ((getBookName() == null) ? 0 : getBookName().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getSectionNum() == null) ? 0 : getSectionNum().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getIsFinish() == null) ? 0 : getIsFinish().hashCode());
        result = prime * result + ((getNetBookId() == null) ? 0 : getNetBookId().hashCode());
        result = prime * result + ((getOriTypeName() == null) ? 0 : getOriTypeName().hashCode());
        result = prime * result + ((getOrigin() == null) ? 0 : getOrigin().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getBookAbstract() == null) ? 0 : getBookAbstract().hashCode());
        result = prime * result + (Arrays.hashCode(getCover()));
        return result;
    }
}