package com.book.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.framework.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crawlertask
 *
 * @mbg.generated do_not_delete_during_merge Wed Mar 11 20:03:54 CST 2020
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CrawlerTask extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.TaskId
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private String taskId;

    /**
     * Database Column Remarks:
     *   任务名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.taskName
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private String taskName;

    /**
     * Database Column Remarks:
     *   任务类型,网站、网页、书
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.taskType
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private String taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.startDate
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.endDate
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private Date endDate;

    /**
     * Database Column Remarks:
     *   抓取页面连接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.seedUrl
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private String seedUrl;

    /**
     * Database Column Remarks:
     *   匹配规则
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.matchRules
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private String matchRules;

    /**
     * Database Column Remarks:
     *   临时目录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.tempDir
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private String tempDir;

    /**
     * Database Column Remarks:
     *   启用的线程数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.threadNum
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private Integer threadNum;

    /**
     * Database Column Remarks:
     *   网页抓取深度，目前尚未测出来深度的具体意义，应该是页面的向下跳转页 -1为不控制深度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.urlDepth
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private Integer urlDepth;

    /**
     * Database Column Remarks:
     *   默认最大抓取页数，即抓取够多少页后，停止，-1为不限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.maxNumber
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private Integer maxNumber;

    /**
     * Database Column Remarks:
     *   实际数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.actualNumber
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private Integer actualNumber;

    /**
     * Database Column Remarks:
     *   是否取图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.hasImage
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private String hasImage;

    /**
     * Database Column Remarks:
     *   是否恢复抓取，还是重新抓取，1为恢复抓取，即继续使用本地库中的种子，进行，0为根据种子重新抓取。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.resume
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private int resume;

    /**
     * Database Column Remarks:
     *   状态，0未开始，1进行中，2已完成
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.taskState
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private String taskState;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawlertask.remark
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crawlertask
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.TaskId
     *
     * @return the value of crawlertask.TaskId
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.TaskId
     *
     * @param taskId the value for crawlertask.TaskId
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.taskName
     *
     * @return the value of crawlertask.taskName
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.taskName
     *
     * @param taskName the value for crawlertask.taskName
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.taskType
     *
     * @return the value of crawlertask.taskType
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.taskType
     *
     * @param taskType the value for crawlertask.taskType
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.startDate
     *
     * @return the value of crawlertask.startDate
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.startDate
     *
     * @param startDate the value for crawlertask.startDate
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.endDate
     *
     * @return the value of crawlertask.endDate
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.endDate
     *
     * @param endDate the value for crawlertask.endDate
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.seedUrl
     *
     * @return the value of crawlertask.seedUrl
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public String getSeedUrl() {
        return seedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.seedUrl
     *
     * @param seedUrl the value for crawlertask.seedUrl
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setSeedUrl(String seedUrl) {
        this.seedUrl = seedUrl == null ? null : seedUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.matchRules
     *
     * @return the value of crawlertask.matchRules
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public String getMatchRules() {
        return matchRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.matchRules
     *
     * @param matchRules the value for crawlertask.matchRules
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setMatchRules(String matchRules) {
        this.matchRules = matchRules == null ? null : matchRules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.tempDir
     *
     * @return the value of crawlertask.tempDir
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public String getTempDir() {
        return tempDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.tempDir
     *
     * @param tempDir the value for crawlertask.tempDir
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setTempDir(String tempDir) {
        this.tempDir = tempDir == null ? null : tempDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.threadNum
     *
     * @return the value of crawlertask.threadNum
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public Integer getThreadNum() {
        return threadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.threadNum
     *
     * @param threadNum the value for crawlertask.threadNum
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setThreadNum(Integer threadNum) {
        this.threadNum = threadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.urlDepth
     *
     * @return the value of crawlertask.urlDepth
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public Integer getUrlDepth() {
        return urlDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.urlDepth
     *
     * @param urlDepth the value for crawlertask.urlDepth
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setUrlDepth(Integer urlDepth) {
        this.urlDepth = urlDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.maxNumber
     *
     * @return the value of crawlertask.maxNumber
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public Integer getMaxNumber() {
        return maxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.maxNumber
     *
     * @param maxNumber the value for crawlertask.maxNumber
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setMaxNumber(Integer maxNumber) {
        this.maxNumber = maxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.actualNumber
     *
     * @return the value of crawlertask.actualNumber
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public Integer getActualNumber() {
        return actualNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.actualNumber
     *
     * @param actualNumber the value for crawlertask.actualNumber
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setActualNumber(Integer actualNumber) {
        this.actualNumber = actualNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.hasImage
     *
     * @return the value of crawlertask.hasImage
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public String getHasImage() {
        return hasImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.hasImage
     *
     * @param hasImage the value for crawlertask.hasImage
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setHasImage(String hasImage) {
        this.hasImage = hasImage == null ? null : hasImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.resume
     *
     * @return the value of crawlertask.resume
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public int getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.resume
     *
     * @param resume the value for crawlertask.resume
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setResume(int resume) {
        this.resume = resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.taskState
     *
     * @return the value of crawlertask.taskState
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public String getTaskState() {
        return taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.taskState
     *
     * @param taskState the value for crawlertask.taskState
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setTaskState(String taskState) {
        this.taskState = taskState == null ? null : taskState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawlertask.remark
     *
     * @return the value of crawlertask.remark
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawlertask.remark
     *
     * @param remark the value for crawlertask.remark
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawlertask
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    @Override
    public Object getPrimaryKey() {
        return this.getTaskId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawlertask
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskId=").append(taskId);
        sb.append(", taskName=").append(taskName);
        sb.append(", taskType=").append(taskType);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", seedUrl=").append(seedUrl);
        sb.append(", matchRules=").append(matchRules);
        sb.append(", tempDir=").append(tempDir);
        sb.append(", threadNum=").append(threadNum);
        sb.append(", urlDepth=").append(urlDepth);
        sb.append(", maxNumber=").append(maxNumber);
        sb.append(", actualNumber=").append(actualNumber);
        sb.append(", hasImage=").append(hasImage);
        sb.append(", resume=").append(resume);
        sb.append(", taskState=").append(taskState);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawlertask
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CrawlerTask other = (CrawlerTask) that;
        return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getTaskName() == null ? other.getTaskName() == null : this.getTaskName().equals(other.getTaskName()))
            && (this.getTaskType() == null ? other.getTaskType() == null : this.getTaskType().equals(other.getTaskType()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getSeedUrl() == null ? other.getSeedUrl() == null : this.getSeedUrl().equals(other.getSeedUrl()))
            && (this.getMatchRules() == null ? other.getMatchRules() == null : this.getMatchRules().equals(other.getMatchRules()))
            && (this.getTempDir() == null ? other.getTempDir() == null : this.getTempDir().equals(other.getTempDir()))
            && (this.getThreadNum() == null ? other.getThreadNum() == null : this.getThreadNum().equals(other.getThreadNum()))
            && (this.getUrlDepth() == null ? other.getUrlDepth() == null : this.getUrlDepth().equals(other.getUrlDepth()))
            && (this.getMaxNumber() == null ? other.getMaxNumber() == null : this.getMaxNumber().equals(other.getMaxNumber()))
            && (this.getActualNumber() == null ? other.getActualNumber() == null : this.getActualNumber().equals(other.getActualNumber()))
            && (this.getHasImage() == null ? other.getHasImage() == null : this.getHasImage().equals(other.getHasImage()))
            && (  this.getResume() ==(other.getResume()))
            && (this.getTaskState() == null ? other.getTaskState() == null : this.getTaskState().equals(other.getTaskState()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawlertask
     *
     * @mbg.generated Wed Mar 11 20:03:54 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getTaskName() == null) ? 0 : getTaskName().hashCode());
        result = prime * result + ((getTaskType() == null) ? 0 : getTaskType().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getSeedUrl() == null) ? 0 : getSeedUrl().hashCode());
        result = prime * result + ((getMatchRules() == null) ? 0 : getMatchRules().hashCode());
        result = prime * result + ((getTempDir() == null) ? 0 : getTempDir().hashCode());
        result = prime * result + ((getThreadNum() == null) ? 0 : getThreadNum().hashCode());
        result = prime * result + ((getUrlDepth() == null) ? 0 : getUrlDepth().hashCode());
        result = prime * result + ((getMaxNumber() == null) ? 0 : getMaxNumber().hashCode());
        result = prime * result + ((getActualNumber() == null) ? 0 : getActualNumber().hashCode());
        result = prime * result + ((getHasImage() == null) ? 0 : getHasImage().hashCode());
        result = prime * result + ( getResume());
        result = prime * result + ((getTaskState() == null) ? 0 : getTaskState().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}